workflows:
  build-ios:
    name: Build iOS
    instance_type: linux
    environment:
      xcode: latest
    scripts:
      - ifconfig | grep 10 | grep inet
      - flutter packages pub get
      - find . -name "Podfile" -execdir pod install \;
      - flutter build ios --release --build-name=1.0.$BUILD_NUMBER --build-number=$BUILD_NUMBER --no-codesign
    artifacts:
      - /tmp/xcodebuild_logs/*.log
  empty:
    name: Test workflow
    labels:
      - QA
      - flavor1
    environment:
      xcode: latest
    scripts:
      - echo "empty"
  greetings:
    inputs:
      name:
        description: Who is greeted?
        default: Codemagic
      name_no_default:
        description: Who is greeted? No default.
    scripts:
      - echo "Hello, ${{ inputs.name }}"
