workflows:
  build-ios:
    name: Build iOS
    instance_type: mac_mini_m1
    environment:
      xcode: 13.3
    scripts:
      - ifconfig | grep 10 | grep inet
      - flutter packages pub get
      - find . -name "Podfile" -execdir pod install \;
      - flutter build ios --release --build-name=1.0.$BUILD_NUMBER --build-number=$BUILD_NUMBER --no-codesign
    artifacts:
      - /tmp/xcodebuild_logs/*.log
  empty:
    name: Empty
    labels:
      - QA
      - flavor1
    environment:
      xcode: 13.3
    scripts:
      - echo "empty"
