workflows:
  build-ios:
    name: Build iOS
    instance_type: mac_mini_m1
    environment:
      xcode: latest
    scripts:
      - ifconfig | grep 10 | grep inet
      - flutter packages pub get
      - find . -name "Podfile" -execdir pod install \;
      - flutter build ios --release --build-name=1.0.$BUILD_NUMBER --build-number=$BUILD_NUMBER --no-codesign
    artifacts:
      - /tmp/xcodebuild_logs/*.log
  deprecated-xcode:
    name: Deprecated Xcode
    instance_type: mac_mini_m1
    inputs:
      xcode_version:
        description: Xcode version
        default: latest
    environment:
      xcode: ${{ inputs.xcode_version }}
    scripts:
      - ifconfig | grep 10 | grep inet
      - flutter packages pub get
      - find . -name "Podfile" -execdir pod install \;
      - flutter build ios --release --build-name=1.0.$BUILD_NUMBER --build-number=$BUILD_NUMBER --no-codesign
    artifacts:
      - /tmp/xcodebuild_logs/*.log
  empty:
    name: Test workflow
    labels:
      - QA
      - flavor1
    environment:
      xcode: latest
    scripts:
      - echo "empty"
  greetings:
    inputs:
      name:
        description: Who is greeted?
        default: Codemagic
      name_no_default:
        description: Who is greeted? No default.
      random_number:
        description: random number
        type: number
    scripts:
      - echo "Hello, ${{ inputs.name }}"
      - echo "Hello, ${{ inputs.name_no_default }}"
      - echo "Hello, ${{ inputs.random_number }}"
  greetings2:
    inputs:
      name:
        description: Who is greeted?
        default: Codemagic
      name_no_default:
        description: Who is greeted? No default.
      random_number:
        description: random number
        type: number
    scripts:
      - export
      - echo "Hello, ${{ inputs.name }}"
      - echo "Hello, ${{ inputs.name_no_default }}"
      - echo "Hello, ${{ inputs.random_number }}"
