workflows:
  run-simulator:
    name: Run Simulator
    max_build_duration: 120
    environment:
      vars:
        XCODE_SCHEME: "Runner"
      flutter: 2.10.5
      xcode: 15.4
    scripts:
      - name: Run Flutter pub get
        script: |
          flutter pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build unsigned .app
        script: |
          xcodebuild -workspace "ios/Runner.xcworkspace" \
            -scheme "Runner" \
            -configuration "Debug" \
            -sdk iphonesimulator \
            -derivedDataPath ios/output
      - name: Install .app on Simulator
        script: |
          # Get the list of all available devices and their states
          devices=$(xcrun simctl list devices --json)

          # Extract the device ID of the currently booted device
          device_id=$(echo $devices | jq -r '.devices[] | .[] | select(.state=="Booted") | .udid')

          # Check if a booted device was found
          if [ -n "$device_id" ]; then
            echo "Currently running iOS simulator device ID: $device_id"
            xcrun simctl install $device_id ./ios/output/Build/Products/Debug-iphonesimulator/Runner.app
          else
            echo "No currently running iOS simulator found."
          fi
    artifacts:
      - ios/output/Build/Products/Debug-iphonesimulator/Runner.app
 
