on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        # required: true
        required: false
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      optional_boolean:
        description: 'True to print to STDOUT'
        # required: true
        type: boolean
      print_tags:
        description: 'Not required boolean'
        required: false
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
      environment:
        required: true
        type: choice
        options:
          - debug
          - staging
          - production

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ inputs.print_tags }} 
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.tags }} 
