on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        # required: true
        required: false
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        # required: true
        type: boolean
      optional_boolean:
        description: 'Not required boolean'
        required: false
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
      environment:
        required: true
        type: choice
        options:
          - debug
          - staging
          - production
      number:
        description: 'Some number'
        required: false
        type: number

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ inputs.print_tags }} 
    steps:
      - run: echo "number is ${{ inputs.number }}"
      - name: Print the input tag to STDOUT
        run: echo "The tags are ${{ inputs.tags }}; env=${{ inputs.environment }}; logLevel=${{ inputs.logLevel }}; optional_boolean=${{ inputs.optional_boolean }}"
